export const metadata = {
    title: 'Weekly Schedule Widget',
    description: 'Generated by next/og',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
